### ISSUE TITLE
DPAT file name issue

### ISSUE THREAD

**Issue by micahvandeusen** [knavesec/Max#10]
In Windows having a `>` in a file name is not allowed resulting in it being `)%`.

The two cases where this is:
Inactive_Accounts_(Last_Used_)%_6mos_Ago)_Cracked.html
Accounts_With_Passwords_Set_)%_1yr_Ago_Cracked.html

The Report.html file links to the file name with `>` resulting in broken links.

**Comment by knavesec** [comment]
Fixed in commit https://github.com/knavesec/Max/commit/41aa72904297a0885686fa721da00f2165939b00
