### ISSUE TITLE
DPAT failure if password is expired

### ISSUE THREAD

**Issue by jvalente-salemstate** [knavesec/Max#24]
The code at line 1104 is causing max.py to fail if I am using the dpat option. 
`num_pass_hashes_list.append([entry['row'][0], entry['row'][1], length, entry['row'][2], datetime.datetime.fromtimestamp(entry['row'][3])], )`

The datetime conversion here fails, and causes the script to exit if a user's password is expired/marked to be changed at next logon.   In AD, this flag being set will set the password's last change date to a blank entry and it appears to be what's throwing the script off 

I double checked that this is the case by moving each of those variables and outputting them one at a time, and it only fails once it hits an an account where that flag was set.  I need to test a change or two, but I think this could quickly be fixed by checking if entry['row'][3] is blank and,if so, setting the output to a different string rather than trying to convert the timestamp. 

Here's a screen capture of the output (after adding two lines to also print usernames and the timestamp without conversion)
<img width="958" alt="image" src="https://user-images.githubusercontent.com/65730960/157897608-1cacbebd-ed41-4f18-bd1c-19a5ba3b27b4.png">

It seems like expired passwords in the .ntds / .dit file are maked with a timestamp of "-1" which is fails when passed to datetime.  The following change resolves it, though I'm not sure if it's the best code-wise 

```
try:

    num_pass_hashes_list.append([entry['row'][0], entry['row'][1], length, entry['row'][2], datetime.datetime.fromtimestamp(entry['row'][3])], )

except:

    num_pass_hashes_list.append([entry['row'][0], entry['row'][1], length, entry['row'][2], ''], )
```

**Comment by knavesec** [comment]
Fixed in most recent commit, thanks for the report!
