### ISSUE TITLE
Incompatibility with neo4j 5.1

### ISSUE THREAD

**Issue by edermi** [knavesec/Max#30]
I'm running on neo4j 5.1 and had to adjust a few things for Max to work again:

- neo4j URI is now `/db/neo4j/tx/commit` instead of `/db/data/transaction/commit`
- `EXISTS(u.cracked)` is not supported anymore, instead `u.cracked IS NOT NULL` must be used

Unfortunately I don't have time for a proper PR right now, hope this helps though

**Comment by almart** [comment]
For those trying to use the dpat module here is a recommendation for the meantime:

Downgrade neo4j to 4.4.13 as recommended by the current BloodHound [documentation](https://bloodhound.readthedocs.io/en/latest/installation/linux.html) 

Steps for Kali/Debian:

`wget -O - https://debian.neo4j.com/neotechnology.gpg.key | sudo apt-key add -`

`echo 'deb https://debian.neo4j.com stable 4.4' | sudo tee /etc/apt/sources.list.d/neo4j.list`

`sudo apt-get update`

Note: Remove any version of neo4j already install 

`apt-get install neo4j=1:4.4.13`

Make sure to use Java 11, install if needed

`update-alternatives --config java`

`neo4j console`

`git switch dpat`

Profit
