### ISSUE TITLE
Incomplete list of unsupported OS

### ISSUE THREAD

**Issue by tigre-bleu** [knavesec/Max#43]
`max.py get-info --unsupported` seems to omit some machines from the list of unsupported OS versus Bloodhound.

I had a case where bloodhound repported a machine with `Windows XP Professional Service Pack 3` while max did not.

**Comment by knavesec** [comment]
Looks like it wasn't searching case sensitive. Updated in [1c302e2](https://github.com/knavesec/Max/commit/1c302e20b7cc4f83c4c844719c2b5e651e545405), let me know if that fixes the problem!
